version: '3.9'

services:
  next-app:
    build:
      context: .
      dockerfile: apps/next-app/Dockerfile
    ports:
      - "3000:3000"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5

  react-app:
    build:
      context: .
      dockerfile: apps/react-app/Dockerfile
    ports:
      - "5173:80"
      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 5
