import '@repo/ui/styles.css';
import './globals.css';

import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import type { Metadata } from 'next';
import { Geist } from 'next/font/google';
import { ReactQueryProvider } from 'services/react-query/query-provider';

const geist = Geist({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <ReactQueryProvider>
        <body className={geist.className}>{children}</body>
        <ReactQueryDevtools initialIsOpen={false} />
      </ReactQueryProvider>
    </html>
  );
}
